Update for open-source Decimal fixes
apple/swift-http-structured-headers pull request #16
Opened 2021-12-28 09:09 UTC by xwu

These are minimal changes to ensure cross-platform and future-proof usage of `Foundation.Decimal` APIs that have incorporated various fixes on Linux that may or may not be incorporated in future Apple releases also.

In brief, the changes always take the absolute value of the significand that's returned from `Decimal.significand` and always in turn provides a positive significand to `Decimal.init(sign:exponent:significand:)`.

2021-12-28 09:12 UTC, xwu commented
cc @Lukasa

2022-01-04 11:55 UTC, Lukasa commented
@swift-server-bot add to allowlist

2022-01-04 12:02 UTC, Lukasa requested changes
This generally looks good! A few minor nits here.

2022-01-04 12:02 UTC, Lukasa commented on Sources/StructuredFieldValues/Encoder/StructuredFieldValueEncoder.swift
> +        let pd = PseudoDecimal(mantissa: significand * (data.isSignMinus ? -1 : 1), exponent: Int(exponent))
```suggestion
        let pd = PseudoDecimal(mantissa: significand * (value.isSignMinus ? -1 : 1), exponent: Int(exponent))
```

2022-01-04 12:02 UTC, Lukasa commented on Sources/StructuredFieldValues/Encoder/StructuredFieldValueEncoder.swift
> +        let pd = PseudoDecimal(mantissa: significand * (data.isSignMinus ? -1 : 1), exponent: Int(exponent))
```suggestion
        let pd = PseudoDecimal(mantissa: significand * (value.isSignMinus ? -1 : 1), exponent: Int(exponent))
```

2022-01-04 13:55 UTC, xwu commented
Thanks for catching that!

2022-01-04 16:24 UTC, Lukasa approved these changes
LGTM, nice fix!

2022-01-04 16:24 UTC, merged