Adopt Sendable
apple/swift-http-structured-headers pull request #23
Opened 2022-05-06 10:30 UTC by Davidde94

Because we don't have a NIO dependency we don't have access to `NIOSendable`. To avoid ` lot of `#if`s throughout the code (making it neater and nicer/easier to read and maintain) I defined my own version, `_Sendable`.

2022-05-06 16:59 UTC, Lukasa requested changes
I was about to overwhelm this PR with stylistic notes, but: there are a bunch of style-only changes. Can they be reverted?

2022-05-06 16:59 UTC, Lukasa commented on Sources/RawStructuredFieldValues/ComponentTypes.swift
> +    var structuredHeadersIsValidToken: Bool {
Can you invert this change?

2022-05-06 16:59 UTC, Lukasa commented on Sources/RawStructuredFieldValues/Errors.swift
> +    static let indexOutOfRange = StructuredHeaderError(.indexOutOfRange)
Can you revert this change?

2022-05-06 16:59 UTC, Lukasa commented on Sources/RawStructuredFieldValues/FieldParser.swift
> +    static func decodingEscapes<Bytes: RandomAccessCollection>(_ bytes: Bytes, escapes: Int) -> String where Bytes.Element == UInt8 {
Can you revert this change?

2022-05-06 16:59 UTC, Lukasa commented on Sources/RawStructuredFieldValues/FieldSerializer.swift
> +    mutating func writeItemFieldValue(_ item: Item) throws -> [UInt8] {
Can you revert this change?

2022-05-06 17:01 UTC, Davidde94 commented
@Lukasa gargh, this all seems to have come from swift-format

2022-05-13 08:41 UTC, Lukasa commented on Sources/RawStructuredFieldValues/Sendable.swift
> +// Copyright (c) 2020 Apple Inc. and the SwiftNIO project authors
This did not get applied.

2022-05-13 16:11 UTC, merged